services:
  classattendancemanagementsystem-backend:
    image: classattendancemanagementsystem-backend
    build:
      context: .
      dockerfile: ClassAttendanceManagementSystem-backend/Dockerfile

